<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员信息"
            }

            ,{
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图信息"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"异常信息类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryGonggao"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"供应商类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryGongyingshang"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"供应商信用等级类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryGongyingshangXinyongdengji"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"疫苗类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryYimiao"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"出入库类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryYimiaoChuruInout"
                    }
                    ,
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"论坛管理",
                        "menuJump":"列表",
                        "tableName":"forum"
                    }
                ],
                "menu":"论坛管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除",
                            "报表"
                        ],
                        "menu":"异常信息管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"异常信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"供应商信息管理",
                        "menuJump":"列表",
                        "tableName":"gongyingshang"
                    }
                ],
                "menu":"供应商信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"孩子信息管理",
                        "menuJump":"列表",
                        "tableName":"haizi"
                    }
                ],
                "menu":"孩子信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除",
                            "报表"
                        ],
                        "menu":"疫苗管理",
                        "menuJump":"列表",
                        "tableName":"yimiao"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除",
                            "报表"
                        ],
                        "menu":"疫苗预约管理",
                        "menuJump":"列表",
                        "tableName":"yimiaoOrder"
                    }
                ],
                "menu":"疫苗管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "出入库",
                            "删除",
                            "报表"
                        ],
                        "menu":"出入库管理",
                        "menuJump":"列表",
                        "tableName":"yimiaoChuruInout"
                    }
                    ,
                    {
                        "buttons":[
                            "订单",
                            "查看",
                            "删除"
                        ],
                        "menu":"出入库详情管理",
                        "menuJump":"列表",
                        "tableName":"yimiaoChuruInoutList"
                    }
                ],
                "menu":"出入库管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"医生管理",
                        "menuJump":"列表",
                        "tableName":"yisheng"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"提醒接种提管理",
                        "menuJump":"列表",
                        "tableName":"yishengLiuyan"
                    }
                ],
                "menu":"医生管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"用户管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"用户管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    },
    {
        "backMenu":[
         {
                "child":[
                    {
                        "buttons":[
                            "新增",
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图信息"
            }
            
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                        ],
                        "menu":"论坛管理",
                        "menuJump":"列表",
                        "tableName":"forum"
                    }
                ],
                "menu":"论坛管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "报表"
                        ],
                        "menu":"异常信息管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"异常信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                        ],
                        "menu":"供应商信息管理",
                        "menuJump":"列表",
                        "tableName":"gongyingshang"
                    }
                ],
                "menu":"供应商信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                        ],
                        "menu":"孩子信息管理",
                        "menuJump":"列表",
                        "tableName":"haizi"
                    }
                ],
                "menu":"孩子信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "报表"
                        ],
                        "menu":"疫苗管理",
                        "menuJump":"列表",
                        "tableName":"yimiao"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "报表"
                        ],
                        "menu":"疫苗预约管理",
                        "menuJump":"列表",
                        "tableName":"yimiaoOrder"
                    }
                ],
                "menu":"疫苗管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "出入库",
                            "报表"
                        ],
                        "menu":"出入库管理",
                        "menuJump":"列表",
                        "tableName":"yimiaoChuruInout"
                    }
                    ,
                    {
                        "buttons":[
                            "订单",
                            "查看",
                        ],
                        "menu":"出入库详情管理",
                        "menuJump":"列表",
                        "tableName":"yimiaoChuruInoutList"
                    }
                ],
                "menu":"出入库管理"
            }
            ,{
                "child":[
                   
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除",
                            "新增"
                        ],
                        "menu":"提醒接种提管理",
                        "menuJump":"列表",
                        "tableName":"yishengLiuyan"
                    }
                ],
                "menu":"提醒接种提管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"医生",
        "tableName":"yisheng"
    }
];

var hasMessage = '';
